services:
  chessvision:
    build: .
    ports:
      - "8000:8000"
    volumes:
        - ./chess_model.tflite:/app/chess_model.tflite
    environment:
      - MODEL_PATH=/app/chess_model.tflite
      - STOCKFISH_PATH=/usr/games/stockfish
      - SEARCH_DEPTH=5
      # GDRIVE_FILE_ID not needed locally since we mount the file directly


